CREATE TABLE IF NOT EXISTS EMPLOYEES (
    DEPARTMENT TEXT,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    SALARY INTEGER,
    AGE INTEGER
);

INSERT INTO EMPLOYEES (DEPARTMENT, NAME, ADDRESS, SALARY, AGE) VALUES 
    ('FINANCE', 'RAM', 'NEW YORK', 10000, 37),
    ('MANUFACTURING', 'RAMESH', 'LOS ANGELES', 9900, 37),
    ('HUMAN RESOURCE', 'SUJIT', 'BOSTON', 8000, 39),
    ('FINANCE', 'SURESH', 'NEW YORK', 9750, 40),
    ('MARKETING', 'AMAN', 'OHIO', 11160, 36),
    ('RETAIL', 'HARSH', 'ATLANTA', 11200, 37);

SELECT * FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT) AS Department_count
FROM EMPLOYEES;

SELECT SUM(SALARY) AS Salary_sum
FROM EMPLOYEES;

SELECT AVG(SALARY) AS Salary_average
FROM EMPLOYEES;

SELECT MIN(SALARY)
FROM EMPLOYEES;

SELECT MAX(SALARY)
FROM EMPLOYEES;